remote_theme: CaptainIRS/hacker-plus-theme

plugins:
   - jekyll-seo-tag
   - jemoji
   - jekyll-sitemap
   - jekyll-github-metadata

title: Eugene "Merclangrat" Bolshakoff
description: The sky above the port was the color of television, tuned to a dead channel. (William Gibson)

collections:
   pages:
      output: true
      permalink: /:name
   rs6000:
      output: true
   pkgsrc-solaris10:
      output: true

