remote_theme: CaptainIRS/hacker-plus-theme
title: Eugene "Merclangrat" Bolshakoff
description: The sky above the port was the color of television, tuned to a dead channel. (William Gibson)

markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
exclude: [
   /*/*/_problems/*,
   scripts
]
plugins:
   - jekyll-seo-tag
   - jemoji
   - jekyll-sitemap
   - jekyll-github-metadata
